version: 2
updates:
  - package-ecosystem: swift
    directories:
      - /SaymarkKit
      - /Tuist
    schedule:
      interval: weekly
      day: monday
    groups:
      swift-routine-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      actions-routine-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5
    labels:
      - dependencies
